name: lyhost-infrastructure
services:
  sonarqube-db:
    image: postgres:15-alpine
    container_name: SonarQube-DB
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SONAR_DB_USER}
      POSTGRES_PASSWORD: ${SONAR_DB_PASSWORD}
      POSTGRES_DB: ${SONAR_DB_NAME}
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - lymon-network

  sonarqube:
    image: sonarqube:community
    container_name: SonarQube
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/${SONAR_DB_NAME}
      SONAR_JDBC_USERNAME: ${SONAR_DB_USER}
      SONAR_JDBC_PASSWORD: ${SONAR_DB_PASSWORD}
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube-db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - lymon-network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: Jenkins
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_NAME=${JENKINS_ADMIN_NAME}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JENKINS_ADMIN_EMAIL=${JENKINS_ADMIN_EMAIL}
      - JENKINS_SONAR_TOKEN=${JENKINS_SONAR_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JENKINS_LOCATION_URL=${JENKINS_LOCATION_URL}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml

    networks:
      - lymon-network

volumes:
  sonarqube_db_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  jenkins_home:

networks:
  lymon-network:
    driver: bridge